fix broken sepainfo import
E   ImportError: cannot import name 'SepaInfo' from partially initialized module 'ibims.com' (most likely due to a circular import) (C:\github\powercloud2lynqtech\.tox\dev\Lib\site-packages\ibims\com\__init__.py)